language: android
dist: trusty
before_install:
  - yes | sdkmanager "platforms;android-30"
android:
  components:
    - build-tools-30.0.1
    - android-30

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-x86-android-30
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
